name: Build Blog
on: 
  issues:
    types: [opened, edited]

jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View the target issue information
        run: |
          echo "repo: ${{ github.repository }}"

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: List all the issues in the repo
        run: |
          echo "Issue URL: ${{ github.event.repository.id }}"
          echo "Issue URL: ${{ github.event.repository.issues_url }}"

      - uses: actions/github-script@v6
        id: check-context
        with:
          script: |
            console.log(context)
            console.log(context.payload.issue.body)
            
      - name: Install Octokit
        run: npm install @octokit/rest

      - uses: actions/github-script@v6
        id: markdown-to-html
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({});
            html = await octokit.request('POST /markdown', {"text": context.payload.issue.body, "mode": "gfm"})
            console.log(html)
            console.log(html.data)
            
      - uses: actions/checkout@v3
          with:
            repository: 'tests-always-included/mo'
        run: |
          export TEST="This is a test"
          echo "Your message: {{TEST}}" | mo
      
      - uses: actions/checkout@v3  
      - name: Read post.html
        run: cat post.html
