name: Build Blog
on: 
  issues:
    types: [opened, edited]

jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View the target issue information
        run: |
          echo "repo: ${{ github.repository }}"
          echo $GITHUB_WORKSPACE

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: List all the issues in the repo
        run: |
          echo "Issue URL: ${{ github.event.repository.id }}"
          echo "Issue URL: ${{ github.event.repository.issues_url }}"

      - uses: actions/github-script@v6
        id: check-context
        with:
          script: |
            console.log(context)
            console.log(context.payload.issue.body)
            
      - name: Install octokit
        run: npm install @octokit/rest

      - uses: actions/github-script@v6
        id: markdown-to-html
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({});
            html = await octokit.request('POST /markdown', {"text": context.payload.issue.body, "mode": "gfm"})
            // console.log(html)
            console.log(html.data)
            return html.data
            // return console.log(html.data)
            
      - name: Show output
        run: |
          echo ${{steps.markdown-to-html.outputs.result}}
            
      - uses: actions/checkout@v3
        with:
          repository: 'tests-always-included/mo'
          path: 'mo'
      
      - name: Escape
        id: escape
        run: |
          html=${{steps.markdown-to-html.outputs.result}}
          echo "before: ${html}"
          html="${html//$'Table'/'TABLE'}"
          html="${html//$'\\n'/\\n}"
          echo "after: ${html}"
          echo "::set-output name=html::$html"
          
      - name: Mustache
        run: |
          echo "POST_HTML is {{REPO}}" | mo/mo
        env:
          REPO: "${{steps.escape.outputs.html}}"
      
      - uses: actions/checkout@v3  
      - name: Read post.html
        run: cat post.html
