name: Build Blog
on: 
  issues:
    types: [opened, edited]

jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View the target issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: List all the issues in the repo
        run: |
          echo "Issue URL: ${{ github.event.repository.id }}"
          echo "Issue URL: ${{ github.event.repository.issues_url }}"

      - uses: actions/github-script@v6
        id: check-context
        with:
          script: |
            console.log(context)

      - uses: actions/github-script@v6
        with:
          script: |
            #const url = "https://api.github.com/repos/narutaro/blog/issues"
            console.log(context)
            #const url = "https://api.github.com/repos/" + context.repo.repo + "/issues"
            #const res = await github.request(url)
            #console.log(res)

