name: Build Blog
on: 
  issues:
    types: [opened, edited]

jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View the target issue information
        run: |
          echo "repo: ${{ github.repository }}"
          echo "workspace: $GITHUB_WORKSPACE"
          echo "repo id: ${{ github.event.repository.id }}"
          echo "issue url: ${{ github.event.repository.issues_url }}"
          echo "issue id: ${{ github.event.issue.id }}" 

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - uses: actions/github-script@v6
        id: check-context
        with:
          script: |
            console.log(context)
            console.log(context.payload.issue.body)
            
      - name: Install octokit
        run: npm install @octokit/rest

      - uses: actions/github-script@v6
        id: markdown-to-html
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({});
            html = await octokit.request('POST /markdown', {"text": context.payload.issue.body, "mode": "gfm"})
            console.log(html.data)
            return html.data
            
      - name: Show output
        run: |
          echo ${{steps.markdown-to-html.outputs.result}}
            
      - name: Escape
        id: escape
        run: |
          html=${{steps.markdown-to-html.outputs.result}}
          echo "before: ${html}"
          html="${html//$'span>\\n'/'span><br>'}"
          html="${html//$'>\\n'/'>'}"
          echo "after: ${html}"
          echo "::set-output name=html::$html"
      
      - uses: actions/checkout@v3
        id: checkout-this-repo  
       
      - uses: actions/checkout@v3
        with:
          repository: 'tests-always-included/mo'
          path: 'mo'
          
      - name: Check files
        run: |
          pwd
          find .
   
      - name: Mustache
        run: |
          cat template/post.template.html | mo/mo > posts/${{ github.event.issue.id }}.html
          cat posts/${{ github.event.issue.id }}.html
        env:
          POST_HTML: "${{steps.escape.outputs.html}}"   
   
      - name: Git setting
        run: |
          git config --local user.email "narusan@mac.com"
          git config --local user.name "${{github.actor}}"
          
      - name: Commit and push post
        run: |
          git add posts/${{github.event.issue.id}}.html
          git commit -m "update" -a
          git pull
          git push origin main
   
