name: Build Blog
on: 
  issues:
    types: [opened, edited]

jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View the target issue information
        run: |
          echo "repo: ${{ github.repository }}"
          echo $GITHUB_WORKSPACE

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: List all the issues in the repo
        run: |
          echo "Issue URL: ${{ github.event.repository.id }}"
          echo "Issue URL: ${{ github.event.repository.issues_url }}"

      - uses: actions/github-script@v6
        id: check-context
        with:
          script: |
            console.log(context)
            console.log(context.payload.issue.body)
            
      - name: Install octokit
        run: npm install @octokit/rest

      - uses: actions/github-script@v6
        id: markdown-to-html
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({});
            html = await octokit.request('POST /markdown', {"text": context.payload.issue.body, "mode": "gfm"})
            console.log(html.data)
            return html.data
            
      - name: Show output
        run: |
          echo ${{steps.markdown-to-html.outputs.result}}
            
      - name: Escape
        id: escape
        run: |
          html=${{steps.markdown-to-html.outputs.result}}
          echo "before: ${html}"
          html="${html//$'span>\\n'/'span><br>'}"
          html="${html//$'>\\n<'/'><'}"
          echo "after: ${html}"
          echo "::set-output name=html::$html"
      
      - uses: actions/checkout@v3  
      - id: checkout-this-repo
      - name: Read tamplate for post
        run: |
          post-template=${cat post.html}
          echo "::set-output name=post-template::$post-template"      
       
      - uses: actions/checkout@v3
        with:
          repository: 'tests-always-included/mo'
          path: 'mo'
       
      - name: Mustache
        run: |
          echo ${POST_TEMPLATE} | mo/mo
        env:
          POST_TEMPLATE: "${{steps.checkout-this-repo.outputs.post-template}}"
          POST_HTML: "${{steps.escape.outputs.html}}"
          
      

